[package]
org = "ballerinax"
name = "twitter"
license= ["Apache-2.0"]
authors = ["Ballerina"]
version= "1.0.1-SNAPSHOT"
export= ["twitter", "twitter.listener"]
repository = "https://github.com/ballerina-platform/module-ballerinax-twitter"
keywords = ["twitter", "social", "communication"]

[build-options]
observability-included=true

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-1.0.1-SNAPSHOT.jar"
groupId = "org.ballerinalang.twitter"
artifactId = "java-wrapper"
version = "1.0.1-SNAPSHOT"
