name: Deployment

on:
  release:
    types: [published]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@slalpha5
              with:
                  args:
                      build -c
              env:
                  CLIENT_ID: ${{ secrets.API_ID }}
                  CLIENT_SECRET: ${{ secrets.API_SECRET }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@slalpha5
              with:
                  args:
                      push
              env:
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
